spring:
  application:
    name: Pharos

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  cors:
    allowed-origins: http://localhost:5173

  jwt:
    secret: ${JWT_SECRET}
    expiration-hours: 8

  flyway:
    enabled: true
    locations: classpath:db/migration